### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by BatoolMM** [Ghozayel/Lextale#6]
Hi Ghozayel, 

I'm very impressed by the package, it looks amazing! You asked me previously about how to develop a logo! 

@Fgazzelloni mentioned this Golem app: https://connect.thinkr.fr/hexmake/ by Colin Fey in R-Ladies Slack!

I'd recommend you write a small blog post about it to help in promoting it and we can add it to RWeekly. Maybe you can use [Medium](https://medium.com/) if you don't have your own blog.

Let me know if it helps!

**Comment by Ghozayel** [comment]
Thank you so much, Batool, for your valuable feedback and suggestions.
You'll stay an inspiration for me. I'll be working on creating a logo and a
personal blog soon to write an article about it, but was wondering, can the
post be a tutorial?

Below are some other points in the package I think they need improvement:

1. The length of the argument: for now it takes 2400 rows. I have tested
this before, it was working well with less but no more than  2400, whivh os
fair enough. However, I tried the function earlier today, it returned an
error when less than 2400 obs were used, meaning that the length must be
2400 rows, no less no more!
Q: Is there a way to make it flexible, any 60 multiplies مضاعفات ٦٠?
Besides that, I'd like to set the length min to 60 observation. The ID and
answer lengths should be equal in length, e.g. if there are 60 observations
under ID there should be 60 observations under answer.

2. The function codes, I need to include 'if statements', i.e. if users
used yes/no instead of binary data (0/1), the function should convert yes
to 1 and no to 0. For now the function lex() only takes binary 0/1. Another
thing is when lex() did the job and calculated the scores of, let's say 40
people, the return() function at the end of code print out the 1st 10
scores in R console. This wasn't ideal so I added write.csv with the hope
it for the output to be saved, but it only pop it inside Rstudio similar to
when we view a file. It's better than before, but how to make it savable,
can be saved?

3. Improve testing: for now the function testing only specifies that input
should be numeric. Numeric data is a must under answer column but in fact
it should not be necessary under ID, e.g. one ID can be a name 'Ahmed'. I
think the current testing codes won't allow this.

4. Updating github page and zenodo accordingly: so far to reflect any
change on github page, I used pkgdown::build_site(). But for Zenodo I'm not
sure if things are synchronised automatically or that I should create
versions/releases everytime major changes were done.

Please let me know if you can help in any. Please ignore if you're too busy
these days, I totally understand ❤️

Best,
Ghozayel

**Comment by Ghozayel** [comment]
Hi Batool,

This helps a lot 👍 Big thanks!

**Comment by Ghozayel** [comment]
I've created the following through Golem app. Do you know where I should attach this in the repo? is it the readme file?

![hex-LexTALE](https://user-images.githubusercontent.com/67930059/193472220-7175497f-5647-4496-828a-ed1e1b8807e7.png)

**Comment by Ghozayel** [comment]
Thanks a lot, Batool.
